name: 'Check if external data changed'
on: ['deployment']

jobs:
  external-data-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: flathub/actions/external-data-checker@master
      env:
        GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
